services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: siga-app
    restart: unless-stopped
    volumes:
      - .:/var/www/
    environment:
      - DB_HOST=db
      - DB_DATABASE=db_siga_satp
      - DB_USERNAME=satp
      - DB_PASSWORD=satpass
    #    ports:
    #      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    container_name: siga_satp-nginx
    restart: on-failure
    ports:
      - "9092:80"
    volumes:
      - .:/var/www/
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:latest
    restart: on-failure
    container_name: siga_satp-db
    ports:
      - 3311:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_siga_satp
      MYSQL_USER: satp
      MYSQL_PASSWORD: satpass
